from __future__ import annotations

from datetime import datetime
from typing import Any


def _pct(value: Any, digits: int = 1) -> str:
    if value is None:
        return "-"
    return f"{100.0 * float(value):.{digits}f}%"


def _pp(value: Any, digits: int = 2) -> str:
    if value is None:
        return "-"
    return f"{100.0 * float(value):+.{digits}f}pp"


def _num(value: Any, digits: int = 2, signed: bool = False) -> str:
    if value is None:
        return "-"
    fmt = f"{{:{'+' if signed else ''}.{digits}f}}"
    return fmt.format(float(value))



def _clock(value: Any) -> str:
    if not value:
        return "-"
    try:
        dt = datetime.fromisoformat(str(value))
        return dt.strftime("%a%H:%M")
    except (TypeError, ValueError):
        return str(value)


def _availability_tag(row: dict[str, Any]) -> str:
    level = str(row.get("availability_evidence_level") or "-")
    source = str(row.get("practice_source") or "-")
    sequence = row.get("practice_sequence") or []
    prior_a = row.get("base_p_active")
    prior_f = row.get("base_p_full_given_active")
    tag = f" ev={level}"
    if sequence:
        tag += f":{source}:{'>'.join(str(x) for x in sequence)}"
    if prior_a is not None and prior_f is not None:
        tag += f" prior={_pct(prior_a,0)}/{_pct(prior_f,0)}"
    return tag


def format_chat_report(payload: dict[str, Any]) -> str:
    """Render a compact, paste-friendly diagnostic report.

    The payload is generated by SeasonGuiService so this formatter never
    recomputes fantasy-model quantities independently of the GUI service.
    """
    lines: list[str] = []
    lines.append(f"FANTASY CHAT DIAGNOSIS {payload.get('version', 'v0.36')}")
    lines.append(
        " ".join(
            [
                f"snapshot={payload.get('snapshot_utc') or '-'}",
                f"season={payload.get('season')}",
                f"week={payload.get('week')}",
                f"team={payload.get('team_name')}",
                f"opponent={payload.get('opponent_name')}",
                f"waiver_rank={payload.get('waiver_rank') or '-'}",
                f"mc={payload.get('mc_scenarios') or '-'}",
            ]
        )
    )

    m = payload.get("matchup") or {}
    lines += [
        "",
        "MATCHUP",
        (
            f"fixed_win={_pct(m.get('fixed_win'))} "
            f"realistic_win={_pct(m.get('realistic_win', m.get('policy_win')))} "
            f"ideal_active_win={_pct(m.get('idealized_active_win'))} "
            f"ideal_full_win={_pct(m.get('idealized_win'))}"
        ),
        (
            f"backup_real={_pp(m.get('realistic_backup_policy_value', m.get('backup_policy_value')))} "
            f"status_timing={_pp(m.get('status_timing_inflation'))} "
            f"workload_info={_pp(m.get('workload_information_inflation'))} "
            f"total_ideal_info={_pp(m.get('information_timing_inflation'))} "
            f"timing={'OK' if m.get('timing_complete') else 'FALLBACK'}"
        ),
        (
            f"our={_num(m.get('our_mean'),1)}±{_num(m.get('our_sd'),1)} "
            f"p10-p90={_num(m.get('our_p10'),1)}-{_num(m.get('our_p90'),1)}"
        ),
        f"opp={_num(m.get('opp_mean'),1)}±{_num(m.get('opp_sd'),1)}",
        f"margin={_num(m.get('margin_mean'),1,True)}±{_num(m.get('margin_sd'),1)} nominal={_num(m.get('nominal_points'),1)}",
    ]

    lines += ["", "LINEUP"]
    for row in payload.get("lineup") or []:
        status = ""
        p_active = row.get("p_active")
        if p_active is not None and float(p_active) < 0.95:
            status = f" status={row.get('status') or '-'}"
        group = row.get("lock_group") or "UNKNOWN"
        state_text = (
            f"F|A={_pct(row.get('p_full_given_active'),0)} "
            f"F/L/O={_pct(row.get('p_full'),0)}/{_pct(row.get('p_limited'),0)}/{_pct(row.get('p_out'),0)}"
        )
        lines.append(
            f"{str(row.get('slot') or ''):<4} {str(row.get('name') or ''):<24} "
            f"op={_num(row.get('mean'),2)} sd={_num(row.get('sd'),2)} "
            f"K={_num(row.get('k'),3)} I={_num(row.get('interaction_factor'),3)} dI={_num(row.get('interaction_delta_ppg'),2,True)} vs={row.get('opponent') or '-'} A={_pct(p_active,0)} {state_text} "
            f"lock={group} kick={_clock(row.get('kickoff_et'))} reveal={_clock(row.get('reveal_et'))}{status}{_availability_tag(row)}"
        )

    opponent_lineup = payload.get("opponent_lineup") or []
    if opponent_lineup:
        lines += ["", "OPPONENT LINEUP"]
        for row in opponent_lineup:
            status = ""
            p_active = row.get("p_active")
            if p_active is not None and float(p_active) < 0.95:
                status = f" status={row.get('status') or '-'}"
            group = row.get("lock_group") or "UNKNOWN"
            state_text = (
                f"F|A={_pct(row.get('p_full_given_active'),0)} "
                f"F/L/O={_pct(row.get('p_full'),0)}/{_pct(row.get('p_limited'),0)}/{_pct(row.get('p_out'),0)}"
            )
            lines.append(
                f"{str(row.get('slot') or ''):<4} {str(row.get('name') or ''):<24} "
                f"op={_num(row.get('mean'),2)} sd={_num(row.get('sd'),2)} "
                f"K={_num(row.get('k'),3)} I={_num(row.get('interaction_factor'),3)} dI={_num(row.get('interaction_delta_ppg'),2,True)} vs={row.get('opponent') or '-'} A={_pct(p_active,0)} {state_text} "
                f"lock={group} kick={_clock(row.get('kickoff_et'))} reveal={_clock(row.get('reveal_et'))}{status}{_availability_tag(row)}"
            )

    symmetry = payload.get("pipeline_symmetry") or {}
    if symmetry:
        lines += [
            "",
            "PREDICTION PIPELINE SYMMETRY",
            (
                f"shared={'YES' if symmetry.get('shared') else 'NO'} "
                f"yield={symmetry.get('yield_builder') or '-'} "
                f"availability={symmetry.get('availability_builder') or '-'} "
                f"interaction={symmetry.get('interaction_builder') or '-'} "
                f"timing={symmetry.get('timing_builder') or '-'} "
                f"lineup={symmetry.get('lineup_optimizer') or '-'}"
            ),
        ]

    if m:
        lines += [
            "",
            "BACKUP POLICY DIAGNOSTICS (SEQUENTIAL, ORDER-DEPENDENT)",
            (
                f"realistic_minus_fixed={_pp(m.get('realistic_backup_policy_value', m.get('backup_policy_value')))} "
                f"status_timing={_pp(m.get('status_timing_inflation'))} "
                f"workload_info={_pp(m.get('workload_information_inflation'))} "
                f"full_ideal_minus_fixed={_pp(m.get('idealized_backup_policy_value'))}"
            ),
            "Attribution order: realistic -> all active/inactive known pre-lock -> FULL/LIMITED also known. Terms interact, so this is not a unique additive decomposition.",
        ]

    uncertain = payload.get("key_uncertainty") or []
    if uncertain:
        lines += ["", "KEY UNCERTAINTY"]
        for row in uncertain:
            lines.append(
                f"{row.get('name')}: game={_num(row.get('game_sd'),2)} "
                f"model={_num(row.get('model_sd'),2)} K={_num(row.get('kinematic_sd'),2)} "
                f"I={_num(row.get('interaction_sd'),2)} total={_num(row.get('total_sd'),2)}"
            )

    opponent_uncertain = payload.get("opponent_key_uncertainty") or []
    if opponent_uncertain:
        lines += ["", "OPPONENT KEY UNCERTAINTY"]
        for row in opponent_uncertain:
            lines.append(
                f"{row.get('name')}: game={_num(row.get('game_sd'),2)} "
                f"model={_num(row.get('model_sd'),2)} K={_num(row.get('kinematic_sd'),2)} "
                f"I={_num(row.get('interaction_sd'),2)} total={_num(row.get('total_sd'),2)}"
            )

    interaction_rows = []
    for side, rows in (("US", payload.get("lineup") or []), ("OPP", payload.get("opponent_lineup") or [])):
        for row in rows:
            if row.get("interaction_source") == "DATA_MC_INTERACTION_GRID_V028":
                interaction_rows.append((side, row))
    if interaction_rows:
        lines += ["", "INTERACTION GRID CORRECTIONS"]
        for side, row in interaction_rows:
            comps = row.get("interaction_components") or {}
            component_text = ",".join(
                f"{name}:{float(info.get('correction') or 1.0):.3f}[N~{float(info.get('support') or 0):.0f}]"
                for name, info in list(comps.items())[:4]
            )
            lines.append(
                f"{side} {row.get('name')}: I={_num(row.get('interaction_factor'),3)} "
                f"delta={_num(row.get('interaction_delta_ppg'),2,True)} sdI={_num(row.get('interaction_sd_ppg'),2)} "
                f"baseline={row.get('interaction_baseline_source') or '-'} support={_num(row.get('interaction_support'),0)} "
                f"components={component_text or '-'}"
            )

    anchors = payload.get("anchor_flags") or []
    if anchors:
        lines += ["", "ESPN ANCHOR FLAGS"]
        for row in anchors:
            lines.append(
                f"{row.get('name')}: model={_num(row.get('model'),2)} "
                f"ESPN={_num(row.get('espn'),2)} delta={_num(row.get('delta'),2,True)} "
                f"op={_num(row.get('operational'),2)}"
            )

    opponent_anchors = payload.get("opponent_anchor_flags") or []
    if opponent_anchors:
        lines += ["", "OPPONENT ESPN ANCHOR FLAGS"]
        for row in opponent_anchors:
            lines.append(
                f"{row.get('name')}: model={_num(row.get('model'),2)} "
                f"Kmodel={_num(row.get('matchup_model'),2)} "
                f"ESPN={_num(row.get('espn'),2)} kind={row.get('espn_kind') or '-'} "
                f"delta={_num(row.get('delta'),2,True)} op={_num(row.get('operational'),2)}"
            )

    hyp = payload.get("hypothetical")
    if hyp and hyp.get("changed"):
        lines += [
            "",
            "HYPOTHETICAL",
            (
                f"selected_fixed_win={_pct(hyp.get('selected_fixed_win'))} "
                f"default_fixed_win={_pct(hyp.get('default_fixed_win'))} "
                f"realistic_win={_pct(hyp.get('realistic_policy_win', hyp.get('policy_win')))} "
                f"ideal_active_win={_pct(hyp.get('idealized_active_policy_win'))} "
                f"ideal_full_win={_pct(hyp.get('idealized_policy_win'))} "
                f"status_timing={_pp(hyp.get('status_timing_inflation'))} "
                f"workload_info={_pp(hyp.get('workload_information_inflation'))} "
                f"delta={_pp(hyp.get('delta_vs_default_fixed'))}"
            ),
            (
                f"selected_score={_num(hyp.get('selected_score_mean'),1)}±{_num(hyp.get('selected_score_sd'),1)} "
                f"default_score={_num(hyp.get('default_score_mean'),1)}"
            ),
        ]
        for row in hyp.get("changes") or []:
            mode = row.get("mode") or "MODEL"
            lines.append(
                f"{row.get('slot')}: {row.get('baseline_name')} -> {row.get('selected_name')} "
                f"mode={mode} delta_pts={_num(row.get('delta_mean'),2,True)}"
            )

    action = payload.get("action")
    if action:
        lines += [
            "",
            "SELECTED ADD/DROP",
            f"ADD {action.get('add_name')} ({action.get('add_position')}) / DROP {action.get('drop_name')} ({action.get('drop_position')})",
            (
                f"delta_H2H={_pp(action.get('delta_h2h_mean'),3)} "
                f"68%=[{_pp(action.get('delta_h2h_p16'),3)},{_pp(action.get('delta_h2h_p84'),3)}] "
                f"P(+/0/-)={_pct(action.get('p_better'),1)}/{_pct(action.get('p_tie'),1)}/{_pct(action.get('p_worse'),1)}"
            ),
            (
                f"P(acquire)={_pct(action.get('p_acquire'),1)} "
                f"league_state_EVdelta={_pp(action.get('expected_delta_utility'),3)} "
                f"week_delta={_num(action.get('week_delta'),2,True)} "
                f"seasonPPG_delta={_num(action.get('season_ppg_delta'),2,True)} "
                f"direct_class={action.get('raw_classification')} league_state_class={action.get('classification')}"
            ),
            (
                f"release_Pclaimed={_pct((action.get('release_response') or {}).get('p_claimed'),1)} "
                f"release_recipient_gain={_num((action.get('release_response') or {}).get('expected_recipient_gain_ppg'),2,True)} "
                f"release_field_shift={_num((action.get('release_response') or {}).get('field_shift_ppg'),2,True)}"
            ),
            (
                f"contingent_diag_option={_num((action.get('option_scarcity') or {}).get('delta_future_option_ppg'),2,True)} "
                f"contingent_diag_stress={_num((action.get('option_scarcity') or {}).get('delta_replacement_scarcity_ppg'),2,True)}"
            ),
        ]

    trade = payload.get("trade")
    if trade:
        lines += [
            "",
            "SELECTED TRADE",
            f"PARTNER {trade.get('partner_name')} · GIVE {', '.join(trade.get('give') or [])} / RECEIVE {', '.join(trade.get('receive') or [])}",
            (
                f"our_delta={_num(trade.get('our_delta_season_ppg'),3,True)}ppg P+={_pct(trade.get('our_p_better'),1)} "
                f"partner_delta={_num(trade.get('partner_delta_season_ppg'),3,True)}ppg P+={_pct(trade.get('partner_p_better'),1)}"
            ),
            (
                f"accept/counter/reject={_pct(trade.get('p_accept'),1)}/{_pct(trade.get('p_counter'),1)}/{_pct(trade.get('p_reject'),1)} "
                f"offer_EV={_num(trade.get('expected_offer_value'),3,True)} classification={trade.get('classification')} MC={trade.get('mc_scenarios')}"
            ),
        ]
        if trade.get('user_auto_drops'):
            lines.append('our_post_trade_release=' + ', '.join(trade.get('user_auto_drops') or []))
        if trade.get('partner_auto_drops'):
            lines.append('partner_post_trade_release=' + ', '.join(trade.get('partner_auto_drops') or []))
        if trade.get('user_auto_adds'):
            lines.append('our_post_trade_FA_fill=' + ', '.join(trade.get('user_auto_adds') or []))
        if trade.get('partner_auto_adds'):
            lines.append('partner_post_trade_FA_fill=' + ', '.join(trade.get('partner_auto_adds') or []))

    closure = payload.get("closure") or {}
    lines += [
        "",
        "CLOSURE",
        (
            f"roster_predictions={closure.get('players', 0)} "
            f"ESPN_anchors={closure.get('anchor_coverage', 0)} "
            f"observed={closure.get('observed_coverage', 0)} "
            f"mean_abs_model_minus_ESPN={_num(closure.get('mean_abs_model_minus_espn'),2)}"
        ),
    ]
    if closure.get("data_mc_rmse") is not None:
        lines.append(
            f"data_MC_bias={_num(closure.get('data_mc_bias'),2,True)} "
            f"data_MC_RMSE={_num(closure.get('data_mc_rmse'),2)} "
            f"mean_data_MC={_num(closure.get('mean_data_over_mc'),3)}"
        )
        if closure.get("base_mc_rmse") is not None:
            lines.append(
                f"interaction_closure base_RMSE={_num(closure.get('base_mc_rmse'),2)} "
                f"corrected_RMSE={_num(closure.get('data_mc_rmse'),2)} "
                f"improvement={_num(closure.get('interaction_rmse_improvement'),2,True)}"
            )

    prospective = closure.get("prospective") or {}
    fantasy = prospective.get("fantasy") or {}
    pulls = prospective.get("pull") or {}
    availability = prospective.get("availability") or {}
    if int(fantasy.get("n") or 0) > 0:
        lines += [
            "",
            "PROSPECTIVE DATA/MC CLOSURE",
            (
                f"weeks={','.join(prospective.get('weeks') or [])} n={fantasy.get('n',0)} "
                f"bias={_num(fantasy.get('bias'),3,True)} MAE={_num(fantasy.get('mae'),3)} "
                f"RMSE={_num(fantasy.get('rmse'),3)} mean_data_MC={_num(fantasy.get('mean_data_over_mc'),3)}"
            ),
        ]
        if fantasy.get("base_rmse") is not None:
            lines.append(
                f"interaction prospective base_RMSE={_num(fantasy.get('base_rmse'),3)} "
                f"corrected_RMSE={_num(fantasy.get('rmse'),3)} "
                f"improvement={_num(fantasy.get('interaction_rmse_improvement'),3,True)}"
            )
        if int(pulls.get("n") or 0) > 0:
            lines.append(
                f"pulls n={pulls.get('n')} mean={_num(pulls.get('mean'),3,True)} sd={_num(pulls.get('sd'),3)}"
            )
        lines.append(
            f"availability_truth n={availability.get('n',0)} brier={_num(availability.get('brier'),4)}"
        )

    flags = payload.get("model_flags") or []
    if flags:
        lines += ["", "MODEL FLAGS"]
        lines.extend(f"- {flag}" for flag in flags)

    health = payload.get("source_health") or []
    if health:
        lines += ["", "SOURCES " + " ".join(f"{row.get('source')}={row.get('status')}" for row in health)]

    return "\n".join(lines).rstrip() + "\n"
