"""Cross-cutting v1.0A observability contracts.

This package is intentionally observational.  It does not import or call
football, market, Monte Carlo, or GUI business logic.
"""

from .adapters import (
    CORE_ADAPTER_REGISTRY,
    SPECIALIST_CHANNELS,
    AdapterRegistry,
    SubsystemAdapter,
)
from .context import RunContext, new_correlation_id
from .correlation import (
    BoundaryKind,
    CorrelationBoundary,
    begin_background_task,
    begin_boundary,
    begin_cli_action,
    begin_service_action,
)
from .diff import DiffEntry, DiffKind, ReplayDiff, diff_replay_bundles, diff_values
from .events import EVENT_SCHEMA_VERSION, StructuredEvent, make_event
from .failure_bundle import (
    FAILURE_BUNDLE_MANIFEST_FILE,
    FAILURE_BUNDLE_SCHEMA_VERSION,
    FAILURE_MEMBER_FILES,
    OMITTED_EXCEPTION_MESSAGE,
    FailureBundle,
    FailureBundleManifest,
    FailureBundleMember,
    FailureBundleVerification,
    load_failure_bundle,
    summarize_exception,
    verify_failure_bundle,
    write_failure_bundle,
)
from .invariants import (
    CORE_INVARIANT_REGISTRY,
    InvariantDefinition,
    InvariantRegistry,
    InvariantResult,
    InvariantSeverity,
    InvariantStatus,
)
from .provenance import (
    SourceProvenance,
    canonical_json_bytes,
    collect_provenance,
    git_source_state,
    read_release_version,
    sha256_bytes,
    sha256_file,
    sha256_json,
    sha256_json_file,
)
from .redaction import (
    BINARY_REPLACEMENT,
    DEFAULT_REPLACEMENT,
    DEPTH_REPLACEMENT,
    RedactionPolicy,
    RedactionResult,
    is_sensitive_key,
    pseudonymize_text,
    redact,
    redact_event,
    redact_value,
    redacted_event_json,
)
from .registry import (
    CORE_EVENT_REGISTRY,
    CORE_SUBSYSTEMS,
    EventDefinition,
    EventLevel,
    EventRegistry,
)
from .replay import (
    ReplayBundle,
    ReplayVerification,
    load_replay_bundle,
    verify_replay_bundle,
)
from .sinks import (
    EventSink,
    FanoutSink,
    HumanTextSink,
    JsonlSink,
    MemorySink,
    emit_all,
    format_human_event,
)
from .snapshots import (
    BUNDLE_MANIFEST_FILE,
    BUNDLE_SCHEMA_VERSION,
    CORE_MEMBER_FILES,
    BundleManifest,
    BundleMember,
    write_snapshot_bundle,
)

__all__ = [
    "AdapterRegistry",
    "BINARY_REPLACEMENT",
    "BUNDLE_MANIFEST_FILE",
    "BUNDLE_SCHEMA_VERSION",
    "BoundaryKind",
    "BundleManifest",
    "BundleMember",
    "CORE_ADAPTER_REGISTRY",
    "CORE_EVENT_REGISTRY",
    "CORE_INVARIANT_REGISTRY",
    "CORE_MEMBER_FILES",
    "CORE_SUBSYSTEMS",
    "CorrelationBoundary",
    "DEFAULT_REPLACEMENT",
    "DEPTH_REPLACEMENT",
    "DiffEntry",
    "DiffKind",
    "EVENT_SCHEMA_VERSION",
    "EventDefinition",
    "EventLevel",
    "EventRegistry",
    "EventSink",
    "FAILURE_BUNDLE_MANIFEST_FILE",
    "FAILURE_BUNDLE_SCHEMA_VERSION",
    "FAILURE_MEMBER_FILES",
    "FailureBundle",
    "FailureBundleManifest",
    "FailureBundleMember",
    "FailureBundleVerification",
    "FanoutSink",
    "HumanTextSink",
    "InvariantDefinition",
    "InvariantRegistry",
    "InvariantResult",
    "InvariantSeverity",
    "InvariantStatus",
    "JsonlSink",
    "MemorySink",
    "OMITTED_EXCEPTION_MESSAGE",
    "RedactionPolicy",
    "RedactionResult",
    "ReplayBundle",
    "ReplayDiff",
    "ReplayVerification",
    "RunContext",
    "SPECIALIST_CHANNELS",
    "SourceProvenance",
    "StructuredEvent",
    "SubsystemAdapter",
    "begin_background_task",
    "begin_boundary",
    "begin_cli_action",
    "begin_service_action",
    "canonical_json_bytes",
    "collect_provenance",
    "diff_replay_bundles",
    "diff_values",
    "emit_all",
    "format_human_event",
    "git_source_state",
    "is_sensitive_key",
    "load_failure_bundle",
    "load_replay_bundle",
    "make_event",
    "new_correlation_id",
    "pseudonymize_text",
    "read_release_version",
    "redact",
    "redact_event",
    "redact_value",
    "redacted_event_json",
    "sha256_bytes",
    "sha256_file",
    "sha256_json",
    "sha256_json_file",
    "summarize_exception",
    "verify_failure_bundle",
    "verify_replay_bundle",
    "write_failure_bundle",
    "write_snapshot_bundle",
]
